on:
  workflow_call:
    inputs:
      artifact-path:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      GITHUB_REQ_TOKE:
        required: true

jobs:
  test-lint:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json
      - run: npm install
      - run: npm run test:lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Installing dependencies
        run: npm install
      - name: Running unit test
        run: npm run test:unit:ci

  build:
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Building Stage
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{inputs.artifact-path}}

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}